# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme: jekyll-agency
url    : "https://valientetechnologies.com"
baseurl: ""

title      : Valiente Technologies
email      : info@valiente.com.tr
description: "Valiente Technologies siber güvenlik ve bilgi teknolojileri alanında hizmet vermekte olan bir şirkettir."
author     : Valiente Technologies
locale: "tr-TR"
logo:
  path: /assets/img/valiente/valientetitle.svg

analytics:
  google: G-FF9YHPMVJL

collections:
  portfolio:

markdown: kramdown

formspree_form_path: "f/xwpbqjer"
